/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.54
 * Generated at: 2015-12-28 15:49:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import org.baraza.web.BWebForms;
import org.baraza.xml.BElement;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ServletContext context = getServletContext();
	String dbconfig = "java:/comp/env/jdbc/database";

	String userIP = request.getRemoteAddr();
	String userName = request.getRemoteUser();

	BWebForms form = new BWebForms(dbconfig);
	String formData = form.getWebForm(request.getParameterMap());
	String formTitle = form.getTitle();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8 no-js\"> <![endif]-->\r\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9 no-js\"> <![endif]-->\r\n");
      out.write("<!--[if !IE]><!-->\r\n");
      out.write("<html lang=\"en\" class=\"no-js\">\r\n");
      out.write("<!--<![endif]-->\r\n");
      out.write("<!-- BEGIN HEAD -->\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\"/>\r\n");
      out.write("\t<title>");
      out.print( pageContext.getServletContext().getInitParameter("web_title") );
      out.write("</title>\r\n");
      out.write("\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t<meta content=\"width=device-width, initial-scale=1\" name=\"viewport\"/>\r\n");
      out.write("\t<meta content=\"Open Baraza Framework\" name=\"description\"/>\r\n");
      out.write("\t<meta content=\"Open Baraza\" name=\"author\"/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- BEGIN GLOBAL MANDATORY STYLES -->\r\n");
      out.write("\t<link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/font-awesome/css/font-awesome.min.css\"  rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/uniform/css/uniform.default.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<!-- END GLOBAL MANDATORY STYLES -->\r\n");
      out.write("\t<!-- BEGIN PAGE LEVEL PLUGIN STYLES -->\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/fullcalendar/fullcalendar.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/jqvmap/jqvmap/jqvmap.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/morris/morris.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!-- END PAGE LEVEL PLUGIN STYLES -->\r\n");
      out.write("\t<!-- BEGIN PAGE STYLES -->\r\n");
      out.write("\t<link href=\"./assets/admin/pages/css/tasks.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/global/plugins/clockface/css/clockface.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-timepicker/css/bootstrap-timepicker.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-colorpicker/css/colorpicker.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"./assets/global/plugins/jquery-tags-input/jquery.tagsinput.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"./assets/global/plugins/select2/select2.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"./assets/global/plugins/jquery-multi-select/css/multi-select.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("    <link href=\"./assets/global/plugins/fullcalendar/fullcalendar.min.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"./assets/global/plugins/bootstrap-toastr/toastr.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"./assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"./assets/admin/pages/css/profile.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\t<link href=\"./assets/global/plugins/jstree/dist/themes/default/style.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- CSS to style the file input field as button and adjust the Bootstrap progress bars -->\r\n");
      out.write("    <link href=\"./assets/global/plugins/jquery-file-upload/css/jquery.fileupload.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- END PAGE STYLES -->\r\n");
      out.write("\t<!-- BEGIN THEME STYLES -->\r\n");
      out.write("\t<!-- DOC: To use 'rounded corners' style just load 'components-rounded.css' stylesheet instead of 'components.css' in the below style tag -->\r\n");
      out.write("    <script >console.info(\"Default Design\") </script>\r\n");
      out.write("    <link href=\"./assets/global/css/components-rounded.css\" id=\"style_components\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"./assets/global/css/plugins.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\t<link href=\"./assets/admin/layout4/css/layout.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\t<link href=\"./assets/admin/layout4/css/themes/light.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\"/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- END THEME STYLES -->\r\n");
      out.write("\t<link rel=\"shortcut icon\" href=\"./assets/logos/favicon.png\"/>\r\n");
      out.write("\r\n");
      out.write("\t<link href=\"./assets/global/plugins/jquery-ui/jquery-ui-1.10.3.custom.min.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("    <link href=\"./assets/jqgrid/css/ui.jqgrid.css\" rel=\"stylesheet\" type=\"text/css\" media=\"screen\" />\r\n");
      out.write("    <link href=\"./assets/admin/layout4/css/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\t<!-- jsgrid css -->\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"./assets/jsgrid-1.2.0/jsgrid.min.css\" />\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"./assets/jsgrid-1.2.0/jsgrid-theme.min.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<!-- END HEAD -->\r\n");
      out.write("<!-- BEGIN BODY -->\r\n");
      out.write("<!-- DOC: Apply \"page-header-fixed-mobile\" and \"page-footer-fixed-mobile\" class to body element to force fixed header or footer in mobile devices -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-closed\" class to the body and \"page-sidebar-menu-closed\" class to the sidebar menu element to hide the sidebar by default -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-hide\" class to the body to make the sidebar completely hidden on toggle -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-closed-hide-logo\" class to the body element to make the logo hidden on sidebar toggle -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-hide\" class to body element to completely hide the sidebar on sidebar toggle -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-fixed\" class to have fixed sidebar -->\r\n");
      out.write("<!-- DOC: Apply \"page-footer-fixed\" class to the body element to have fixed footer -->\r\n");
      out.write("<!-- DOC: Apply \"page-sidebar-reversed\" class to put the sidebar on the right side -->\r\n");
      out.write("<!-- DOC: Apply \"page-full-width\" class to the body element to have full width page without the sidebar menu -->\r\n");
      out.write("<body class=\"page-header-fixed page-sidebar-closed-hide-logo page-sidebar-closed-hide-logo page-footer-fixed\">\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN HEADER -->\r\n");
      out.write("<div class=\"page-header navbar navbar-fixed-top\">\r\n");
      out.write("\t<!-- BEGIN HEADER INNER -->\r\n");
      out.write("\t<div class=\"page-header-inner\">\r\n");
      out.write("\t\t<!-- BEGIN LOGO -->\r\n");
      out.write("\t\t<div class=\"page-logo\">\r\n");
      out.write("\t\t\t<a href=\"index.jsp\">\r\n");
      out.write("\t\t\t<img src=\"./assets/logos/logo_header.png\" alt=\"logo\" style=\"margin: 20px 10px 0 10px; width: 107px;\" class=\"logo-default\"/>\r\n");
      out.write("\t\t\t</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END LOGO -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- BEGIN PAGE TOP -->\r\n");
      out.write("\t\t<div class=\"page-top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- BEGIN TOP NAVIGATION MENU -->\r\n");
      out.write("\t\t\t<div class=\"top-menu\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav pull-right\">\r\n");
      out.write("\t\t\t\t\t<!-- BEGIN USER LOGIN DROPDOWN -->\r\n");
      out.write("\t\t\t\t\t<!-- END USER LOGIN DROPDOWN -->\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END TOP NAVIGATION MENU -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- END PAGE TOP -->\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- END HEADER INNER -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- END HEADER -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN CONTAINER -->\r\n");
      out.write("<div class=\"page-container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<!-- BEGIN Portlet PORTLET-->\r\n");
      out.write("\t\t\t<div class=\"portlet light\">\r\n");
      out.write("\t\t\t\t<div class=\"portlet-title\">\r\n");
      out.write("\t\t\t\t\t<div class=\"caption\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"icon-speech\"></i>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"caption-subject bold uppercase\"> ");
      out.print( formTitle );
      out.write("</span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"actions\">\r\n");
      out.write("\t\t\t\t\t  ");
 if(form.getEntryFormId() != null) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn btn-circle btn-default\" onclick=\"getFormValues();\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-pencil\"></i> Save </a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn btn-circle btn-default\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-plus\"></i> Submit </a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn btn-circle btn-default btn-icon-only fullscreen\"></a>\r\n");
      out.write("\t\t\t\t\t  ");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"portlet-body\">\r\n");
      out.write("\t\t\t\t\t<div class=\"scroller\" style=\"height:575px\" data-rail-visible=\"1\" data-rail-color=\"yellow\" data-handle-color=\"#a1b2bd\">\r\n");
      out.write("\t\t\t\t\t\t<form id='barazaForm' name='barazaForm' method='post' action='form.jsp'>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( form.getFormTabs() );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print( formData );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- END Portlet PORTLET-->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- END CONTAINER -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN FOOTER -->\r\n");
      out.write("<div class=\"page-footer\">\r\n");
      out.write("\t<div class=\"page-footer-inner\">\r\n");
      out.write("\t\t2015 &copy; Open Baraza. <a href=\"http://dewcis.com\">Dew Cis Solutions Ltd.</a> All Rights Reserved\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"scroll-to-top\">\r\n");
      out.write("\t\t<i class=\"icon-arrow-up\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- END FOOTER -->\r\n");
      out.write("<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->\r\n");
      out.write("<!-- BEGIN CORE PLUGINS -->\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"./assets/global/plugins/respond.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/excanvas.min.js\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-migrate.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-ui/jquery-ui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!--<script src=\"./jquery-ui-1.11.4.custom/jquery-ui.min.js\"  type=\"text/javascript\"></script>-->\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery.blockui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery.cokie.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/uniform/jquery.uniform.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- END CORE PLUGINS -->\r\n");
      out.write("<!-- BEGIN PAGE LEVEL PLUGINS -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/jquery.vmap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/ckeditor/ckeditor.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/select2/select2.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->\r\n");
      out.write("<script src=\"./assets/global/plugins/morris/morris.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/morris/raphael-min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery.sparkline.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- END PAGE LEVEL PLUGINS -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js\"></script>\r\n");
      out.write("<!-- The Load Image plugin is included for the preview images and image resizing functionality -->\r\n");
      out.write("<!--<script src=\"//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js\"></script>-->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/vendor/load-image.min.js\"></script>\r\n");
      out.write("<!-- The Canvas to Blob plugin is included for image resizing functionality -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js\"></script>\r\n");
      out.write("<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js\"></script>\r\n");
      out.write("<!-- The basic File Upload plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload.js\"></script>\r\n");
      out.write("<!-- The File Upload processing plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js\"></script>\r\n");
      out.write("<!-- The File Upload image preview & resize plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js\"></script>\r\n");
      out.write("<!-- The File Upload audio preview plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js\"></script>\r\n");
      out.write("<!-- The File Upload video preview plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js\"></script>\r\n");
      out.write("<!-- The File Upload validation plugin -->\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- BEGIN PAGE LEVEL SCRIPTS -->\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/scripts/metronic.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/layout4/scripts/layout.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/layout4/scripts/demo.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/pages/scripts/index3.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/pages/scripts/tasks.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/pages/scripts/components-pickers.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-multi-select/js/jquery.multi-select.js\" type=\"text/javascript\" ></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jquery-multi-select/js/jquery.quicksearch.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/clockface/js/clockface.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/jstree/dist/jstree.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/admin/pages/scripts/ui-tree.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/bootstrap-toastr/toastr.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- END PAGE LEVEL SCRIPTS -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"./assets/jqgrid/js/i18n/grid.locale-en.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./assets/jqgrid/js/jquery.jqGrid.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- calendar-->\r\n");
      out.write("<!-- IMPORTANT! fullcalendar depends on jquery-ui.min.js for drag & drop support -->\r\n");
      out.write("<script src=\"./assets/global/plugins/moment.min.js\"></script>\r\n");
      out.write("<script src=\"./assets/global/plugins/fullcalendar/fullcalendar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jsgrid for sub form editing-->\r\n");
      out.write("<script src=\"./assets/jsgrid-1.2.0/jsgrid.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    jQuery(document).ready(function() {\r\n");
      out.write("        Metronic.init(); // init metronic core componets\r\n");
      out.write("        Layout.init(); // init layout\r\n");
      out.write("\r\n");
      out.write("        $('.date-picker').datepicker({\r\n");
      out.write("            autoclose: true\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\t\tUITree.init();\r\n");
      out.write("\r\n");
      out.write("\t\t$('.clockface').clockface({\r\n");
      out.write("            format: 'hh:mm a',\r\n");
      out.write("            trigger: 'manual'\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $('.clockface-toggle').click(function (e) {\r\n");
      out.write("            e.stopPropagation();\r\n");
      out.write("            var target = $(this).attr('data-target');\r\n");
      out.write("            $('#' + target ).clockface('toggle');\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\t\t$('.select2me').select2({\r\n");
      out.write("            placeholder: \"Select an option\",\r\n");
      out.write("            allowClear: true\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\t");
      out.print( form.printSubForm() );
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction getFormValues() {\r\n");
      out.write("        var str = '';\r\n");
      out.write("\t\tvar jsonForm = {};\r\n");
      out.write("        var elem = document.getElementById('barazaForm').elements;\r\n");
      out.write("        for(var i = 0; i < elem.length; i++) {\r\n");
      out.write("\t\t\tif(!(elem[i].name == null || elem[i].name == \"\", elem[i].value == null || elem[i].value == \"\")) {\r\n");
      out.write("\t\t\t\tjsonForm[elem[i].name] = elem[i].value;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\t\tfor\t(i = 0; i < db_list.length; i++) {\r\n");
      out.write("\t\t\tjsonForm[db_list[i]] = eval(db_list[i]);\r\n");
      out.write("\t\t}\r\n");
      out.write("console.log(jsonForm);\r\n");
      out.write("console.log(JSON.stringify(jsonForm));\r\n");
      out.write("\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype: \"POST\",\r\n");
      out.write("\t\t\turl: \"ajaxupdate?fnct=formupdate&entry_form_id=\" + ");
      out.print(form.getEntryFormId());
      out.write(",\r\n");
      out.write("\t\t\tdata: \"json=\" + JSON.stringify(jsonForm),\r\n");
      out.write("\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\tsuccess: function(data){\r\n");
      out.write("console.log(\"Data: \" + data);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tfailure: function(errMsg) {\r\n");
      out.write("console.log(\"Error: \" + errMsg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<!-- END BODY -->\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
 	form.close(); 
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /form.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("contextPath");
    // /form.jsp(3,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /form.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("mainPage");
    // /form.jsp(4,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setValue("forms.jsp");
    // /form.jsp(4,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setScope("page");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }
}
